### ISSUE TITLE
Add tags to Application Insight context after initialisation

### ISSUE THREAD

**Issue by randompixel** [zerodep/pino-applicationinsights#1]
Hey,

In order to add the authenticated user to the Application Insight logs, for Node, you set
```
applicationinsights.defaultClient.context.tags["ai.user.authUserId"]
```
where `applicationinsights` is the imported v2 library.

Is there a way of doing this here? I can't quite work it out from the docs.

Also, I'd like to initialise the logger at the start of the application, but I won't know the authorised user until the request is made and I've processed the JWT, so I'd need to be able to add the tags post-initialisation. (using `pino-http`, the logger context is on the `req` object - is there a way of interacting with that?

**Comment by paed01** [comment]
Tricky. I have been attempting to instrument the inner workings of applicationinsights in the past, but got lost in the [dependency forrest](https://www.npmjs.com/package/applicationinsights/v/2.9.6?activeTab=dependencies). I'll make another try, but no promises. Not sure about the npm approach of MS because it will be even harder in [v3](https://bundlephobia.com/package/applicationinsights@3.4.0) :bomb:.

**Comment by paed01** [comment]
I have added ability to forward `tagOverrides` to appinsights, see the added example app. Though, I did not manage to get the user id to the logging, as far as I can see in any case. The overridden version works!? Please experiment with the example app and share your findings.

**Comment by paed01** [comment]
Doh! Wait a sec. I forgot to forward the tagOverrides to appinsights.

**Comment by paed01** [comment]
Presto! `npm i @0dep/pino-applicationinsights@latest` to get user id to trace logging.

Edit:
The example adds async hook to pick up the authenticated user in the logging

**Comment by randompixel** [comment]
Wow @paed01, thanks so much for looking at this. I'll have a go on Monday morning and let you know.

**Comment by paed01** [comment]
No problem. Glad someone is using it besides me.

**Comment by randompixel** [comment]
This is now sending through the userId tags as required.

The example was useful as a starting point as well, so thanks again for that!

Are you able to tag the code / release it as a new version?
